"""Create RouteOS operational schema."""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("locations", sa.Column("id", sa.Integer, primary_key=True), sa.Column("code", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("type", sa.String(32), nullable=False), sa.Column("latitude", sa.Float, nullable=False), sa.Column("longitude", sa.Float, nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("vehicles", sa.Column("id", sa.Integer, primary_key=True), sa.Column("identifier", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("type", sa.String(32), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("latitude", sa.Float), sa.Column("longitude", sa.Float), sa.Column("current_location_id", sa.Integer, sa.ForeignKey("locations.id")), sa.Column("current_journey_id", sa.Integer), sa.Column("last_seen", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("journeys", sa.Column("id", sa.Integer, primary_key=True), sa.Column("identifier", sa.String(32), nullable=False, unique=True), sa.Column("vehicle_id", sa.Integer, sa.ForeignKey("vehicles.id"), nullable=False), sa.Column("origin_location_id", sa.Integer, sa.ForeignKey("locations.id"), nullable=False), sa.Column("destination_location_id", sa.Integer, sa.ForeignKey("locations.id")), sa.Column("status", sa.String(24), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("arrived_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("people", sa.Column("id", sa.Integer, primary_key=True), sa.Column("identifier", sa.String(32), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("current_location_id", sa.Integer, sa.ForeignKey("locations.id")), sa.Column("current_journey_id", sa.Integer, sa.ForeignKey("journeys.id")), sa.Column("current_vehicle_id", sa.Integer, sa.ForeignKey("vehicles.id")), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("users", sa.Column("id", sa.Integer, primary_key=True), sa.Column("email", sa.String(160), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(24), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("assignments", sa.Column("id", sa.Integer, primary_key=True), sa.Column("person_id", sa.Integer, sa.ForeignKey("people.id"), nullable=False), sa.Column("journey_id", sa.Integer, sa.ForeignKey("journeys.id"), nullable=False), sa.Column("vehicle_id", sa.Integer, sa.ForeignKey("vehicles.id"), nullable=False), sa.Column("joined_at", sa.DateTime(timezone=True)), sa.Column("left_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(24), nullable=False))
    op.create_table("events", sa.Column("id", sa.Integer, primary_key=True), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("entity_type", sa.String(32), nullable=False), sa.Column("entity_id", sa.Integer), sa.Column("timestamp", sa.DateTime(timezone=True)), sa.Column("actor_id", sa.Integer, sa.ForeignKey("users.id")), sa.Column("location_id", sa.Integer, sa.ForeignKey("locations.id")), sa.Column("source", sa.String(24), nullable=False), sa.Column("payload", sa.JSON, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)))
    op.create_table("alerts", sa.Column("id", sa.Integer, primary_key=True), sa.Column("severity", sa.String(16), nullable=False), sa.Column("alert_type", sa.String(48), nullable=False), sa.Column("entity_type", sa.String(32), nullable=False), sa.Column("entity_id", sa.Integer), sa.Column("message", sa.Text, nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("resolved_by", sa.Integer, sa.ForeignKey("users.id")), sa.Column("payload", sa.JSON, nullable=False))

def downgrade():
    for table in ("alerts", "events", "assignments", "people", "journeys", "vehicles", "locations", "users"): op.drop_table(table)
